name: Build, Bundle, and Publish for macOS
on:
  push:
    branches:
      - cicd/test_macos
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build x86_64 binary
        run: cargo build --release --target x86_64-apple-darwin
      - name: Build ARM64 binary
        run: cargo build --release --target aarch64-apple-darwin
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: target/release
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-target-
      - name: Create a universal binary from the x86_64 and ARM64 binaries
        run: lipo -create -output directory_summarizer -arch x86_64 target/x86_64-apple-darwin/release/directory_summarizer -arch arm64 target/aarch64-apple-darwin/release/directory_summarizer
      - name: Create *.app folder structure
        run: mkdir -p directory_summarizer.app/Contents/MacOS
      - name: Move binary into the *.app folder
        run: cp directory_summarizer directory_summarizer.app/Contents/MacOS/directory_summarizer
      - name: Compress *.app directory to *.zip, preserving resource fork and Finder information
        run: ditto -c -k --sequesterRsrc --keepParent directory_summarizer.app directory_summarizer.zip
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: directory_summarizer.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            # New Release

            This is a new release of Directory Summarizer.

            ## Changelog

            - Add feature X
            - Fix bug Y
