name: Build, Bundle, and Publish for macOS
on:
  push:
    branches:
      - cicd/test_macos
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build x86_64 project
        run: cargo build --release --target x86_64-apple-darwin
      - name: Build ARM64 project
        run: cargo build --release --target aarch64-apple-darwin
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: target/release
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-target-
      - name: Bundle for macOS
        run: |
          lipo -create -output directory_summarizer -arch x86_64 target/x86_64-apple-darwin/release/directory_summarizer -arch arm64 target/aarch64-apple-darwin/release/directory_summarizer
          mkdir -p directory_summarizer.app/Contents/MacOS
          cp directory_summarizer directory_summarizer.app/Contents/MacOS/directory_summarizer
          chmod +x directory_summarizer.app/Contents/MacOS/directory_summarizer
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v$(cargo metadata --format-version | jq -r '.packages | .[] | select(.name=="directory_summarizer") | .version')
          files: "directory_summarizer.app"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            # New Release

            This is a new release of Directory Summarizer.

            ## Changelog

            - Add feature X
            - Fix bug Y
